Repository PetConnectingTeam/pet-connecting, pull requests merged in 2024-12, with the labels that each got.

#116 fixed delete pets
  api/app/routes.py
Labels: bug, enhancement

#121 endpoint to sign contract, sent by mail to pet owner and caregiver
  api/app/__init__.py
  api/app/routes.py
  api/app/templates/legal.html
  api/requirements.txt
  docker-compose.yml
Labels: enhancement, epic

#125 fix: assigned services can't be reassigned unless unassigned first
  api/app/routes.py
Labels: bug

#129 Insert signatures contract
  api/app/models.py
  api/app/routes.py
  api/app/templates/legal.html
Labels: enhancement

#133 Feature/rating system
  frontend/messages/en.json
  frontend/messages/es.json
  frontend/src/app/[locale]/home/page.tsx
  frontend/src/app/[locale]/petsProfile/[petID]/page.tsx
Labels: enhancement

#141 Feature/rating system
  frontend/src/api/api.ts
  frontend/src/app/[locale]/components/bar-sidebar.tsx
  frontend/src/app/[locale]/components/signature.tsx
Labels: enhancement
